"""Add visibility and checkout fields

Revision ID: 7fc7efdf6e86
Revises: 1582781d1b7f
Create Date: 2026-06-09 18:38:23.212945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc7efdf6e86'
down_revision: Union[str, Sequence[str], None] = '1582781d1b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_sessions', sa.Column('customer_name', sa.String(), nullable=True))
    op.add_column('booking_sessions', sa.Column('customer_email', sa.String(), nullable=True))
    op.add_column('booking_sessions', sa.Column('customer_address', sa.String(), nullable=True))
    op.add_column('booking_sessions', sa.Column('delivery_method', sa.String(), nullable=True))
    op.add_column('events', sa.Column('visible_from', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('is_hidden', sa.Boolean(), nullable=False))
    op.add_column('events', sa.Column('offers_physical_tickets', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'offers_physical_tickets')
    op.drop_column('events', 'is_hidden')
    op.drop_column('events', 'visible_from')
    op.drop_column('booking_sessions', 'delivery_method')
    op.drop_column('booking_sessions', 'customer_address')
    op.drop_column('booking_sessions', 'customer_email')
    op.drop_column('booking_sessions', 'customer_name')
    # ### end Alembic commands ###
