"""split_address

Revision ID: fc77f7b7f31e
Revises: 7fc7efdf6e86
Create Date: 2026-06-09 19:01:36.454163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc77f7b7f31e'
down_revision: Union[str, Sequence[str], None] = '7fc7efdf6e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_street', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('customer_street_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('customer_city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('customer_zip', sa.String(), nullable=True))
        batch_op.drop_column('customer_address')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_address', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('customer_zip')
        batch_op.drop_column('customer_city')
        batch_op.drop_column('customer_street_number')
        batch_op.drop_column('customer_street')

    # ### end Alembic commands ###
